CREATE TABLE IF NOT EXISTS `payments` (
  `paymentID` int NOT NULL AUTO_INCREMENT,
  `appointmentID` int NOT NULL,
  `patientID` int NOT NULL,
  `doctorID` int NOT NULL,
  `merchantOrderId` varchar(120) NOT NULL,
  `transactionId` varchar(120) DEFAULT NULL,
  `paymentGateway` varchar(50) DEFAULT 'PayHere',
  `amount` decimal(10,2) NOT NULL DEFAULT '0.00',
  `currency` varchar(10) NOT NULL DEFAULT 'LKR',
  `paymentStatus` enum('Pending','Completed','Failed','Cancelled') DEFAULT 'Pending',
  `payhereStatusCode` varchar(20) DEFAULT NULL,
  `paymentMethod` varchar(50) DEFAULT NULL,
  `receiptUrl` varchar(255) DEFAULT NULL,
  `gatewayResponse` json DEFAULT NULL,
  `notifyPayload` json DEFAULT NULL,
  `notifySignature` varchar(255) DEFAULT NULL,
  `verifiedAt` timestamp NULL DEFAULT NULL,
  `notifyProcessedAt` timestamp NULL DEFAULT NULL,
  `createdAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`paymentID`),
  UNIQUE KEY `uq_payments_merchantOrderId` (`merchantOrderId`),
  UNIQUE KEY `uq_payments_transactionId` (`transactionId`),
  KEY `idx_payments_appointmentID` (`appointmentID`),
  KEY `idx_payments_patientID` (`patientID`),
  KEY `idx_payments_doctorID` (`doctorID`),
  KEY `idx_payments_status` (`paymentStatus`),
  KEY `idx_payments_createdAt` (`createdAt`),
  CONSTRAINT `payments_ibfk_1` FOREIGN KEY (`appointmentID`) REFERENCES `appointments` (`appointmentID`) ON DELETE CASCADE,
  CONSTRAINT `payments_ibfk_2` FOREIGN KEY (`patientID`) REFERENCES `patient` (`patientID`) ON DELETE CASCADE,
  CONSTRAINT `payments_ibfk_3` FOREIGN KEY (`doctorID`) REFERENCES `doctor` (`doctorID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;